### ISSUE TITLE
Multi Thread Not working as expected

### ISSUE THREAD

**Issue by blazerguns** [Keyang/node-csvtojson#52]
Hi Guys,

I pulled in the latest code change which support multi cpu support. However somehow it seem to not work as expected. Here is the sample code  I am using.

var data = fs.readFileSync(config.destination, 'utf8');
parse_csv(data)
.then(function (object) {
 console.log(object)
}

function parse_csv_internal(data, onComplete){
    
    var csvConverter = new Converter({constructResult:true, workerNum:4});
    csvConverter.fromString(data,function(err,jsonObj) {
      if (err){
          log("Parse CSV Internal Function Error" + err);
          onComplete(err, null);
      } else {
          log('Parse CSV Internal function has finished!');
          onComplete(null, jsonObj);
      }
    });

    csvConverter.on("end_parsed", function(jsonObj) {
      //final result poped here as normal.
    });
}

function parse_csv(csv_data) {
  return new Promise(function (fulfill, reject) {
    parse_csv_internal(csv_data, function(err, result) {
      if (err == null) {
        fulfill(result);
      } else {
        log('Parse CSV function has an error!');
        return reject(err);
      }
    });
  });
}

It takes like 20mins to finish because of
 node             0.0   00:00.15 5    0    28    10M    0B    0B     9766 9766 sleeping *0[1]           0.00000 0.00000    501  5119      156     50        25        450        85        258        0         0         0.0   varun           N/A  N/A  N/A  N/A  N/A  N/A
9769  node             0.0   00:00.16 5    0    28    10M    0B    0B     9766 9766 sleeping *0[1]           0.00000 0.00000    501  5116      153     50        25        452        85        251        0         0         0.0   varun           N/A  N/A  N/A  N/A  N/A  N/A
9768  node             0.0   00:00.16 5    0    28    10M    0B    0B     9766 9766 sleeping *0[1]           0.00000 0.00000    501  5149      158     50        25        450        85        207        0         0         0.0   varun           N/A  N/A  N/A  N/A  N/A  N/A
9767  curl             0.0   00:00.05 2    0    38    1996K  0B    0B     9767 420  sleeping *0[4]           0.00000 0.00000    501  1335      122     119       46        1755+      250       817+       9         0         0.0   varun           N/A  N/A  N/A  N/A  N/A  N/A
9766  node             100.1 07:35.63 7/1  0    37    

I see 4 threads but only one thread is doing work. Others are sleeping. What am I doing wrong here?

**Comment by Keyang** [comment]
It worked with read stream:
```js
var c=new Converter({"construct":true,"workerNum":4});

var rs=fs.createReadStream("./csvdata");
rs.pipe(c);
```
I did not expect pass large csv string directly due to memory reasons. But it is a bug and I will take a look.

Thanks.

~Keyang

**Comment by Keyang** [comment]
I have patched this in version 0.4.1.
It should now work.

Regards,
Keyang

**Comment by blazerguns** [comment]
I tried with

"csvtojson": "^0.4.1",

Still have the same problem. It seem like 3 other threads are sleeping.

**Comment by blazerguns** [comment]
{
  "name": "csvtojson",
  "description": "A tool concentrating on converting csv data to JSON with customised parser supporting",
  "author": {
    "name": "Keyang Xiang",
    "email": "keyang.xiang@gmail.com"
  },
  "homepage": "http://keyangxiang.com/blog/csv2json/",
  "bugs": {
    "url": "https://github.com/Keyang/node-csvtojson/issues"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/Keyang/node-csvtojson.git"
  },
  "contributors": [
    {
      "name": "Keyang Xiang",
      "email": "keyang.xiang@gmail.com"
    },
    {
      "name": "Tom Dodson",
      "email": "t3dodson@gmail.com"
    }
  ],
  "version": "0.4.1",

**Comment by Keyang** [comment]
Hi,
I cannot re-produce this issue with 0.4.1.
I have created a test project here: https://github.com/Keyang/testcsvtojson
It simply load csv data string and pass it into converter with 4 workers.
See CPU usage below:
node	82.1	2.81	
node	75.7	2.53	
node	74.6	2.51	
node	73.9	2.48	

Please give a try and let me know how it works on your machine.

1. Checkout the git repo
2. npm install
3. node ./test.js

~Keyang

**Comment by Keyang** [comment]
Not reproducible.
